### ISSUE TITLE
data question

### ISSUE THREAD

**Issue by matthewfdaniels** [the-pudding/pop-up-story#39]
for the section where you have `Here’s how cisgender queer artists with more than 5 chart appearances sing about relationships:` and `We also found 3 songs where non-binary and genderfluid artists sing about relationships with men. Here’s what those lyrics look like:`, why weren't those in the chart from before? I was actually expecting sam smith to be on there, but I understand that since they identify as neither a man/woman, it wouldn't be same-sex?

**Comment by jadiehm** [comment]
@matthewfdaniels correct. i'm unsure of the best why to handle non-binary artists. I could just put them in one chart and do a better job explaining that I can't count non-binary artists using masculine pronouns as same-gender.
