### ISSUE TITLE
finish lil nas x animations

### ISSUE THREAD

**Issue by jadiehm** [the-pudding/pop-up-story#40]

**Comment by jadiehm** [comment]
pole on load
quotes
reverse scroll

**Comment by russellgoldenberg** [comment]
i'm not sure I 100% get what you are going for without talking through it. There might be some hacks to cobble together on top of what you have, but my hunch is you need to rewrite it. We can talk on Wed.

**Comment by jadiehm** [comment]
- [ ] pole height
